### PR TITLE
Crypto Market App PR

### PR DESCRIPTION
**Pull request by mertkantaroglu**
Hello,

In this project, I :

- [ ] Created React App
- [ ] Created router function and routes 
- [ ] Created components and related files
- [ ] Created redux store and slices files
- [ ] Connected React with Redux
- [ ] Used store, actions and reducers in React
- [ ] Used React props
- [ ] Handled events in a React app
- [ ] Added testing files
- [ ] Wrote tests to test the program
- [ ] Added styling
- [ ] Added and updated Readme file
- [ ] Added linters and fix linter erros
- [ ] Added [video presentation](https://www.loom.com/share/1f17167ac9154013b5c65b969a818ca5) to Readme file 

Looking forward to your response.

Thanks.

### CODE REVIEW

**Comment by thecodechaser** [comment]
@mertkantaroglu Please check slack for my message

**Review by thecodechaser — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @mertkantaroglu👋, 

### You are doing a marvelous job on the React capstone project and this is one of the best projects I have seen so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

image

## To Highlight 🎉
- All tests are passed. ✔️
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Nice UI design. ✔️
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



## Required Changes ♻️

- [ ] Please make sure to record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes as requested in the project requirements. Please add video link in the PR. The content of the video should include:
  - A description of the project.
  - A demo of the project features.
  - You should also highlight some interesting piece of code.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Tufahel — CHANGES_REQUESTED** [review]
# Status: Required Changes :recycle:
Hi @mertkantaroglu :wave: 

Well done. :+1:  
You need to fix some issues before moving to the next project. :running_man: 

## Highlights 🌟

Alt Text

✔️ Linters checks are passing.
✔️ Readme is professional.
✔️ Application is working fine.
✔️ Tests are passing.


## Required Changes ♻️

- [x] It's awesome that you have added the video link in README. 👍 But, you need to add the video link in the `Pull request description` also. It's easy for the reviewer to review and for your future use, it's good to document the project summary in one place.
  - Here (Pull request description), you need to add the video link:
  - image

- [x] There are some requirements that you need to cover in your video presentation.
  - A description of the project.
  - A demo of the project features.
  - You should also highlight some interesting pieces of code.
  > You have `described the project`, and shown a `demo of the project features` perfectly. But you missed showcasing/highlighting some interesting pieces of code from your project that you are proud of. 
  > ***Kindly record another video and showcase/highlight some interesting pieces of code from your project that you are proud of.***
  > It is because, in the future, you need to perform video presentations for various big companies, so it needs to be professional and you feel confident that you can do it as you have practiced it a lot in the Microverse.

## Optional suggestions 🤷‍♂️

- ***[Optional]*** Kindly consider using capital letters as the first letter of the commit messages, as it is more professional.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [Mail](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mertkantaroglu** [comment]
Hey @Tufahel

Thanks for your review. I updated PR details but I think on the video you missed the point I mentioned about the Search bar as the code I am proud of.

**Comment by Tufahel** [comment]
> Hey @Tufahel
> 
> Thanks for your review. I updated PR details but I think on the video you missed the point I mentioned about the Search bar as the code I am proud of.

Hello @mertkantaroglu 👋, you only mention about `solving the search bar as you didn't want to use enter key`. You can mention how you have solved this problem and how was this special to you. Showcase/explain a bit more.

**Review by DammyShittu — CHANGES_REQUESTED** [review]
Hi @mertkantaroglu,

## Highlights
✔️ Neat user interface and design

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [x] As requested previously, you need to redo your presentation video and highlight the piece of code that you are proud of. This means you need to open your code editor (for example VS Code, if that is what you are using) and show the actual code. A suggestion would be: since you mentioned you are proud of the search functionality, you can perform a quick overview of the code for this feature in your editor.

  This practice can come in handy in future company/demo presentations where you may have to walk some people through your code and show how a feature was implemented -  and in some cases why a certain coding approach was used.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by KDlamini — APPROVED** [review]
### Hi  @mertkantaroglu 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your project is very impressive. You have outdone yourself with the search algorithm. Fantastic!!! 🔥🔥🔥
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ Good API integration using Axios and Redux store
✔️ Events, actions, and Redux state management implemented correctly
✔️ Well done with the search filter 🍾 
✔️ The design guidelines for Colours, Typography, and Layout are followed
✔️ single page application (SPA) using `react-router-dom`

## Video Presentation 

✔️ The presentation video presents the features of the project with a maximum length of 5 minutes.
✔️ The video contains a clear and objective description of the project in professional English. 
✔️ The video contains a demo of the project, highlighting all the project features.
✔️ The video contains a highlight about a piece of the code the student finds interesting or is proud of making.

# Status: Approved ✔️ 

oscars-standing-ovation
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mertkantaroglu** [comment]
Thank you for your kind words @KDlamini 👍

**Pull request merged**
